#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party/birdie
source $dir/functions/third-party/dropbox
source $dir/functions/third-party/fontforge
source $dir/functions/third-party/gnome
source $dir/functions/third-party/google-chrome
source $dir/functions/third-party/keybase
source $dir/functions/third-party/minecraft
source $dir/functions/third-party/oracle-java
source $dir/functions/third-party/owncloud
source $dir/functions/third-party/rvm
source $dir/functions/third-party/slack
source $dir/functions/third-party/spotify
source $dir/functions/third-party/steam
source $dir/functions/third-party/sublime-text3
source $dir/functions/third-party/vocal
source $dir/functions/third-party/insync


# Install Third-Party Applications
function thirdparty {
    eval `resize`
    THIRDPARTY=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'insync'            'Insync GDrive client' \
        'dropbox'           'Dropbox' \
        'google-chrome'     'Google Chrome' \
        'fontforge'         'FontForge' \
        'rvm'               'Ruby Version Manager (RVM)' \
        'slack'             'Slack' \
        'spotify'           'Spotify' \
        'vocal'             'Vocal podcast app' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $THIRDPARTY
    else
        clear && main
    fi
}

