#!/bin/bash

dir="$(dirname "$0")"

UTILS="$dir/data/utilities.list"

# Install Favourite System Utilities
function install_utils {
    if (eval `resize` && whiptail --title \
        "Favourite System Utilities"  --yesno \
        "Current list of favourite system utilities: \n\n$(cat $UTILS) \n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        # Feel free to change the contents of 'utilities.list' in the data folder to whatever suits your preference.
        $SUDOCMD apt-get install -y --no-install-recommends $(cat $UTILS)
        check_exit "$?"
        # Done
        show_success 'Done.'
        whiptail --title "Finished" --msgbox "Installation complete." 8 78
        main
    else
        clear && main
    fi
}

function texlive {
    if (eval `resize` && whiptail --title \
        "TeXLive installation" --yesno \
        "This action will download & install the latest available version of TeXLive.\n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
    # Install
    show_info "Preparing directories and dowloading TeX distribution..."
    WHERE=${PWD}
    TMPDIR="$WHERE/texlive-install"
    mkdir -p $TMPDIR
    cd $TMPDIR
    wget -O texlive.tar.gz http://mirror.switch.ch/ftp/mirror/tex/systems/texlive/tlnet/install-tl-unx.tar.gz
    tar xzf texlive.tar.gz; rm -f texlive.tar.gz
    cd install-tl-*
    show_info "Starting TeXLive installer..."
    show_info "Choose a different directory if you don't want a system-wide installation."
    show_warning 'Requires root privileges'
    $SUDOCMD ./install-tl -repository http://mirror.switch.ch/ftp/mirror/tex/systems/texlive/tlnet
    exitstatus=$?
    if [[ $exitstatus != 0 ]]; then
        show_error 'Something went wrong with TeXLive installation! Exit and reinstall again.'
        clear && main
    else
        show_info 'TeXLive installation went fine! Now configuring binaries and paths ...'
    fi
    cd - >/dev/null
    show_info 'Setting up path for TeX bins...'
    echo 'export PATH=/opt/texbin:${PATH}' > texlive.sh
    $SUDOCMD mv texlive.sh /etc/profile.d/
    $SUDOCMD mkdir -p /opt
    YEAR=$(whiptail --title "Year of TeXLive distribution installed?" --nocancel --inputbox "Year:\n" 8 80 "2015" 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [[ $exitstatus != 0 || ${#YEAR} > 4 ]]; then
        show_error 'You specified a wrong year (perhaps badly formatted; only 4 digits are needed)'
        clear && main
    fi
    INSTALLDIR=$(whiptail --title "Where did you install TeXLive?" --nocancel --inputbox "Install directory:\n(leave default if you installed in '/usr/local')" 8 80 "/usr/local" 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [[ $exitstatus != 0 ]]; then
        show_error 'Something went wrong when specifying TeXLive installation path.' && sleep 2
        clear && main
    fi
    case `uname -i` in
        i386)
            TEXPATH="$INSTALLDIR/texlive/2015/bin/i386"
            ;;
        x86_64)
            TEXPATH="$INSTALLDIR/texlive/2015/bin/x86_64-linux"
            ;;
        *)
            show_error "Error in architecture supported. Check it and re-run installation." && main
            ;;
    esac
    $SUDOCMD ln -fs $TEXPATH/bin /opt/texbin
    show_info 'TeX bin directory set. You MUST logout/login to make this change effective.' && sleep 2
    show_info "Check that the command 'which tex' will give you '/opt/texbin'. If this is the case, enjoy TeXLive." && sleep 2
    show_info 'Making TeX aware of system fonts...'
    $SUDOCMD cp $(kpsewhich -var-value TEXMFSYSVAR)/fonts/conf/texlive-fontconfig.conf \
        /etc/fonts/conf.d/09-texlive.conf
    $SUDOCMD fc-cache -fsv
    cd $WHERE; rm -rf texlive-install
    show_info 'Done.'
    whiptail --title "Finished" --msgbox "TeXLive installation complete. Happy TeXing!" 8 78
    main
    else
        clear && main
    fi
}

function utilities {
    eval `resize`
    UTIL=$(whiptail \
        --notags \
        --title "Install utilities" \
        --menu "\nWhat would you like to do?" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES -12 )) \
        install_utils 'Install utilities packages' \
        texlive 'Install latest TeXLive distribution' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [[ $exitstatus == 0 ]]; then
        clear && $UTIL
    else
        clear && main
    fi
}
